language: node_js
node_js:
  - 12

os: linux

before_script:
  - npm install -g gulp-cli
script: npm run build

deploy:
  provider: pages
  edge: true
  repo: SVendittelli/svendittelli.github.io
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: master
  local_dir: dist/
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
