#.travis.yml

dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "10.4"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm test
  - npm run report-coverage

after_success:
  - npm run build:prod

deploy:
  provider: pages
  skip-cleanup: true
  repo: SVendittelli/svendittelli.github.io
  local_dir: dist/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target-branch: master
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change