language: node_js
node_js:
  - 12

os: linux
addons:
  chrome: stable # make sure Chrome is available

before_install:
  - npm install -g @lhci/cli # install lighthouse CI

before_script:
  - npm install -g gulp-cli
script:
  - npm run build # build site
  - lhci autorun # run lighthouse CI

deploy:
  provider: pages
  edge: true
  repo: SVendittelli/svendittelli.github.io
  token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  target_branch: master
  local_dir: dist/
  on:
    branch: master

notifications:
  email:
    on_failure: always
    on_success: change
